### ISSUE TITLE
hot files stat

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#10]
Hi, is scheduled ly creation extended statistics for hls module, for example sees most hot files for the time period, traffic etc

?

**Comment by whatvn** [comment]
hello, 
No. By serving hls we've transformed nginx into application server which is more complicated than serving static or proxying (or FCGI) only. By adding statistic we must add other layers: share memory to store statistics, computing to count and compute which object is hot (or not)...

If you really want to do it, I suggest you should implement at balancer layer (Redirector, most CDN use 302 redirect to balance cdn request)

**Comment by arty777** [comment]
no, CDN not planned ,  i just interesting, thanks for the info

**Comment by whatvn** [comment]
CDN is just a theory. it depends on how you implement your `routing` gateway. 
For example, if you use my redirect balancer: https://github.com/whatvn/py-balancer , modify it a bit to work with redis, each request for media file will be written to redis using sorted set, then after a period of time, you can find which object is hot (or not) by zrange by-score, and route request to hot server.
