### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#12]
On this file i usually get 
2015/05/23 07:23:47 [alert] 6556#0: worker process 7830 exited on signal 11 (core dumped)

Why? 

ffmpeg -i ./1.mp4
ffmpeg version 2.6.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --enable-libx264 --enable-static --disable-opencl --enable-gpl --enable-libfdk-aac --enable-nonfree --enable-shared
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './176169.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Su 2015 from Exy
    encoder         : HandBrake 0.10.1 2015030800
  Duration: 01:39:18.96, start: 0.000000, bitrate: 452 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1024x576, 319 kb/s, 24 fps, 24 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(rus): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : Stereo

give me your skype , and i transfer mp4 file for you
my skype artyinua

**Comment by whatvn** [comment]
could you please upload it to somewhere so I can download? 
Or just provide me direct link to mp4 file on your server. 
Thanks

**Comment by arty777** [comment]
File is here 
http://www.ex.ua/483946877946

**Comment by arty777** [comment]
Is reproduce problem? You acknowledge the problem?

**Comment by whatvn** [comment]
No, I have trouble downloading file from url you provided, the speed is not so good.
I will look at this and feed back ASAP.

**Comment by whatvn** [comment]
this file give me error too. but I dont get core dump here, it just report a silly arg that was sent to malloc() and my code use malloc everywhere, it's hard to debug what produces the error. 
it would be great if you can send me core dump file

**Comment by arty777** [comment]
I do not see at the dump file, only the entry in the log as I have shown above, you also receive the same record in erorr log? The dump file should be somewhere to go then? Where?

**Comment by whatvn** [comment]
well, I find out what is the problem. 
the problem is your media file, metadata report that its duration is  01:39:18.95, but it's actually just 43 minutes long, I don't know why, maybe your or someone who use video muxing tool which has problem by its self.

But this introduces a bug in our module, cause core dump and worker exit if there's a bad media file likes that. 
344538d8fb6ecac639d0a28c7e70a74936eab75c fixed error showed above. 

@arty777 : Do you convert/re-convert media file before publish it to the website?

**Comment by arty777** [comment]
> its duration is 01:39:18.95, but it's actually just 43 minutes long
> How do you define it?
> do you convert/re-convert media file before publish it to the website?
> Yes of course I convert files to MP4, as well as hundreds of other files that do not have problems, no error messages I have not seen when conwert this file

**Comment by arty777** [comment]
PS file size is 321 Mb (337 211 392 byte)

**Comment by whatvn** [comment]
example your streaming domain is: domain.com, to request m3u8 file:
http://domain.com/issue.m3u8
Replace m3u8 with mp4 and paste url to chrome browser, let it play. Seek to more than 2/3 of video, your video will end immediately. 
Or just look at duration of file in your player

**Comment by arty777** [comment]
duration file in flash player is 01:39:18 , via chrome (direct link to mp4) 01:39:18 , plz check again file is here http://embed.china-cdn88nmbwacdnln8hq8qwe.com/embed.php?mid=176169

**Comment by whatvn** [comment]
hmm, the file you uploaded before is 146MB. they are different?

**Comment by arty777** [comment]
No , it's same file http://www.ex.ua/483946877946 , i see 337,209,408 file size by link 

Apparently you're it somehow not completely downloaded

**Comment by whatvn** [comment]
I download that file again, it has size 322M, and I don't get any trouble playing the file. Even with adaptive or not.

**Comment by arty777** [comment]
i still have error , Please see details in  file attached http://www.ex.ua/399578959909

**Comment by whatvn** [comment]
can you run your test nginx with error file with nginx's configuration above after run sudo ulimit -c unlimited and send me core dump file:

```
daemon off;
master_process off;
```

**Comment by arty777** [comment]
i does't see dump file , how get it? see log attached http://www.ex.ua/399578959909
filename error_1.zip

**Comment by whatvn** [comment]
with previous nginx configuration, cd /path/to/nginx ; gdb ./sbin/nginx
Request m3u8 file, nginx will reply with 500 response. On console (still in gdb shell), run `bt`, copy its output

**Comment by arty777** [comment]
root@test:/usr/local/nginx2# gdb ./sbin/nginx2
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./sbin/nginx2...done.
(gdb) bt
No stack.
(gdb) bt
No stack.
(gdb) bt
No stack.
(gdb) bt
No stack.
(gdb) bt
No stack.
(gdb) run bt
Starting program: /usr/local/nginx2/sbin/nginx2 bt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
nginx: invalid option: "bt"
[Inferior 1 (process 19211) exited with code 01](gdb) run bt
Starting program: /usr/local/nginx2/sbin/nginx2 bt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
nginx: invalid option: "bt"
[Inferior 1 (process 19219) exited with code 01](gdb) bt
No stack.

**Comment by whatvn** [comment]
did you request m3u8 in-order to crash nginx before using `bt` command?

**Comment by arty777** [comment]
i see my issue . Whait a few min

**Comment by arty777** [comment]
1. i run gdb ./sbin/nginx1
2. Request problem file
3. in gdb shell run bt i see
   (gdb) bt No stack.
   :(
   what my mistake?

**Comment by whatvn** [comment]
`2. Request problem file`
did you get 500 error?

**Comment by arty777** [comment]
yes , 502

**Comment by arty777** [comment]
i find core 
here is http://www.ex.ua/399578959909
it's  help to resolve issue?

**Comment by arty777** [comment]
any updates?

**Comment by whatvn** [comment]
Well, your nginx build does not match mine, maybe you're using different Nginx version, different OS and /or different code base. 
On my machine/and production server, we are using nginx-1.6.2 and lastest source code of this module, your file can be played well.

**Comment by arty777** [comment]
try this plz , ant tell me pls is everything is fine http://nginx.org/download/nginx-1.9.1.tar.gz

**Comment by whatvn** [comment]
that version is not stable, from version 1.8 nginx introduces many new features which I dont think all of those are stable (although they marked it as stable).
If you dont need threads, tcp load balancing, I recommend using 1.6 branch, it's more stable and durable.

**Comment by arty777** [comment]
nginx 1.6.3 , with last your module ver
2015/05/29 09:42:57 [alert] 24330#0: worker process 24331 exited on signal 11 (core dumped)
:(

nginx version: nginx/1.6.3
built by gcc 4.8.2 (Ubuntu 4.8.2-19ubuntu1)
configure arguments: --prefix=/usr/local/nginx/work/nginx1 --sbin-path=/usr/local/nginx/work/nginx1/sbin/nginx1 --conf-path=/usr/local/nginx/ work/nginx1/conf/nginx.conf --pid-path=/usr/local/nginx/work/nginx1/nginx1.pid --error-log-path=/usr/local/nginx/work/nginx1/log/error.log -- lock-path=/usr/local/nginx/work/nginx1/nginx.lock --http-log-path=/usr/local/nginx/work/nginx1/log/access.log --http-client-body-temp-path=/u sr/local/nginx/work/nginx1/temp/client --http-proxy-temp-path=/usr/local/nginx/work/nginx1/temp/proxy --http-fastcgi-temp-path=/usr/local/ngi nx/work/nginx1/temp/fastcgi --http-uwsgi-temp-path=/usr/local/nginx/work/nginx1/temp/uwsgi --http-scgi-temp-path=/usr/local/nginx/work/nginx1 /temp/scgi --with-file-aio --without-http_autoindex_module --without-http_browser_module --without-http_fastcgi_module --without-http_geo_mod ule --without-http_empty_gif_module --without-http_memcached_module --without-http_ssi_module --without-http_userid_module --without-http_gzi p_module --with-http_perl_module --with-debug --with-http_secure_link_module --with-http_stub_status_module --add-module=/usr/local/nginx/ngx _http_estreaming_module-master

**Comment by arty777** [comment]
I reconvert file again ... 

all fine ...
