### ISSUE TITLE
Does module support live streams or VoD only?

### ISSUE THREAD

**Issue by reduxionist** [whatvn/ngx_http_estreaming_module#14]
It's not clear to me from the readme whether I need to have the entire video available as a file beforehand or not; can this module be used with a stream that is being published live?

Thanks for sharing your code!

**Comment by whatvn** [comment]
hello,

At this time it’s for VOD only. To work with livestream you can use nginx rtmp module which is written by nginx developers, it works great as far as i know.

**Comment by reduxionist** [comment]
Understood; thanks for the quick response!
