### ISSUE TITLE
what happend in new ver of module?

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#15]
I is an older version of the module, from about May 2015, in my version I get a playlist
http://myserver.com/view/100053.m3u8?secl=qAmpzDxGNQ2zPhHSsZHwQw&sect=1438625784

 inside - ALL FINE ,. here
# EXTINF: 10.010,

0 / 177138.ts?Secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125
# EXTINF: 10.010,

1 / 177138.ts? Secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125
# EXTINF: 10.010,

.......  

  The new version (now downloaded) within:
(i don't see here!!! ?Secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125)
# EXTINF: 10.678,

0 / 208.ts
# EXTINF: 11.220,

3 / 208.ts
# EXTINF: 11.595,

7 / 208.ts
# EXTINF: 11.137,

11 / 208.ts
# EXTINF: 12.304,

15 / 208.ts

Sec links for ts does;s not create normally in new ver, I'm getting on, respectively, 403
how to fix?

**Comment by whatvn** [comment]
@arty777 could you please try with commit above?

**Comment by arty777** [comment]
i see bug time to time (lastest release)
0/133442/org.ts?secl=XyAXW65nTcSnPx03s9Nfvw&sect=1438789082
#EXTINF:13.080,
2/133442/org.ts?secl=XyAXW65nTcSnPx03s9Nfvw&sect=1438789082
#EXTINF:17.320,
7/133442/org.ts?secl=XyAXW65nTcSnPx03s9Nfvw&sect=1438789082
#EXTINF:13.480,
11/133442/org.ts?secl=XyAXW65nTcSnPx03s9Nfvw&sect=1438789082
#EXTINF:13.880,
14/133442/org.ts?secl=XyAXW65nTcSnPx03s9Nfvw&sect=1438789082
#EXTINF:13.000,
18/133442/org.ts?secl=XyAXW65nTcSnPx03s9Nfvw&sect=1438789082

 normally when 
#EXTINF:10.010,
0/177138.ts?secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125
#EXTINF:10.010,
1/177138.ts?secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125
#EXTINF:10.010,
2/177138.ts?secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125
#EXTINF:16.350,
3/177138.ts?secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125
#EXTINF:14.807,
5/177138.ts?secl=gthP6Wd-O-WU6rD3NDAYmQ&sect=1438627125

**Comment by whatvn** [comment]
hmm, it seems ok on my side. 
Here is my configuration:

``` java

 secure_link           $arg_st,$arg_e;
secure_link_md5       "axcDxSVnsGkAKvqhqOh$host$arg_e";
if ($secure_link = "")  { return 403; }
if ($secure_link = "0") { return 410; }
          rewrite ^(.*)/(adbr)/([0-9]+p)/([0-9]+)/(.*ts)\??(.*) $1/$5?video=$4&$2=true&vr=$3&$6 last;
            rewrite ^(.*)/(adbr)/([0-9]+p)/(.*\.m3u8)\??(.*) $1/$4?$2=true&vr=$3&$5 last;
            rewrite ^(.*)/(org)/(.*\.m3u8)\??(.*) $1/$3?$2=true&$6 last;
            rewrite ^(.*)/(org)/([0-9]+)/(.*\.ts)\??(.*) $1/$4?video=$3&$2=true&$5 last;
            rewrite ^(.*)/([0-9]+)/(.*\.ts)\??(.*)  $1/$3?video=$2&$4 last;
        location / {
        streaming;
        error_log /data/log/error.log ;
        root   /data/stream;
        segment_length 5;
        hls_buffer_size 1m;
        hls_max_buffer_size 50m;
        mp4_buffer_size 1m;
        mp4_max_buffer_size 500m;
    }

```

``` bash
curl "http://127.0.0.1/out.m3u8?st=I41rNtHxHOHiViU63hSGow&e=2147483647"
#EXTM3U
#EXT-X-ALLOW-CACHE:NO
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1560000,RESOLUTION=640x360,CODECS="mp4a.40.2, avc1.4d4015"
org/out.m3u8?st=I41rNtHxHOHiViU63hSGow&e=2147483647
```

``` bash
 curl "http://127.0.0.1/org/out.m3u8?st=I41rNtHxHOHiViU63hSGow&e=2147483647" 
#EXTM3U
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-VERSION:4
#EXTINF:5.121,
0/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.401,
11/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.441,
23/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
35/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.081,
46/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.081,
58/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.001,
69/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.240,
80/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.240,
92/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.361,
103/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.161,
116/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
#EXTINF:5.361,
2751/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
2763/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.161,
2774/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.201,
2785/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.201,
2796/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
2807/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.161,
2819/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.001,
2831/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.321,
2843/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.321,
2855/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.041,
2867/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.001,
2878/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.041,
2889/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.441,
2901/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.240,
2913/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.401,
2925/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.401,
2938/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.081,
2951/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.161,
2962/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
2974/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
2986/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.361,
2997/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
3009/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
3020/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.240,
3031/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:5.281,
3042/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXTINF:3.520,
3053/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
#EXT-X-ENDLIST
```

``` bash
 wget "http://127.0.0.1/org/3053/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647"
--2015-08-06 11:10:38--  http://127.0.0.1/org/3053/out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38352 (37K) [video/MP2T]
Saving to: _out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647.1_

100%[====================================================================================================================================================================================================>] 38,352      --.-K/s   in 0.001s  

2015-08-06 11:10:38 (37.0 MB/s) - _out.ts?st=I41rNtHxHOHiViU63hSGow&e=2147483647.1_ saved [38352/38352]
```

can you please provide your current configuration?

**Comment by arty777** [comment]
It works, but approx 3-rd time (at the same video) i get incorrect m3u8, in my old ver all fine
my config 

rewrite ^(._)/(org)/(._.m3u8)\??(._) $1/$3?$2=true&$6 last;
rewrite ^(._)/(org)/([0-9]+)/(._.ts)\??(._) $1/$4?video=$3&$2=true&$5 last;
rewrite ^(._)/([0-9]+)/(._.ts)\??(.*)  $1/$3?video=$2&$4 last;

location /view/ {

##### secure all content

```
rewrite /view/(.*)\.m3u8$ /video/$1.m3u8;
rewrite /view/(.*)\.ts$   /video/$1.ts;
```

}
...............
...............
location ~ "/video/(.*).m3u8$" {

secure_link $arg_secl,$arg_sect;
secure_link_md5 MYsecretpassword$arg_sect$remote_addr;
proxy_cache_key $proxy_host$uri$arg_org$arg_video;

if ($secure_link = "")  { return 403; }
if ($secure_link = "0") { return 410; }

location ~ "/video/(.*).ts$" {

secure_link $arg_secl,$arg_sect;
secure_link_md5 MYsecretpassword$arg_sect$remote_addr;
proxy_cache_key $proxy_host$uri$arg_org$arg_video;

if ($secure_link = "")  { return 403; }
if ($secure_link = "0") { return 410; }

**Comment by whatvn** [comment]
ok, I tested a again and got that bug too. I'm trying to fix that, please be patient

**Comment by arty777** [comment]
Nice news ... ))

**Comment by whatvn** [comment]
could you please test commit above?

**Comment by arty777** [comment]
015/08/07 18:06:58 [alert] 5569#0: worker process 5794 exited on signal 6 (core dumped)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x21a1f40] overread end of atom 'colr' by 1 bytes
**\* stack smashing detected _**: nginx: worker process terminated
2015/08/07 18:06:59 [alert] 5569#0: worker process 5792 exited on signal 6 (core dumped)
*_\* stack smashing detected _**: nginx: worker process terminated
*_\* stack smashing detected _**: nginx: worker process terminated
2015/08/07 18:06:59 [alert] 5569#0: worker process 5801 exited on signal 6 (core dumped)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x21ee760] overread end of atom 'colr' by 1 bytes
2015/08/07 18:06:59 [alert] 5569#0: worker process 5766 exited on signal 6 (core dumped)
*_\* stack smashing detected _**: nginx: worker process terminated
*_\* stack smashing detected ***: nginx: worker process terminated
2015/08/07 18:06:59 [alert] 5569#0: worker process 5789 exited on signal 6 (core dumped)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x219df00] overread end of atom 'colr' by 1 bytes
2015/08/07 18:06:59 [alert] 5569#0: worker process 5753 exited on signal 6 (core dumped)

old module work fine ......

**Comment by arty777** [comment]
Old ver 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x8d68c0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x806380] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x8d68c0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x991360] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x93b540] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x9917a0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x9b2420] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x992780] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xb3b8a0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xa75be0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x9f5780] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xa83620] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x852ba0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xbde1a0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xd08ec0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xf55d60] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xa2afe0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x8067a0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x852760] overread end of atom 'colr' by 1 bytes

no any core dumped , all work fine

**Comment by whatvn** [comment]
Which link are you trying to request to nginx?

**Comment by arty777** [comment]
What is the difference?  the old version does not fall in core dumped (((( 

http://site.com/view/75996.m3u8?secl=2ShFLGHnvE-l051Ttsdefg&sect=1439044538
http://site.com/view/org/75996.m3u8?secl=2ShFLGHnvE-l051Ttsdefg&sect=1439044538
http://site.com/view/org/0/75996.ts?secl=2ShFLGHnvE-l051Ttsdefg&sect=1439044538

**Comment by whatvn** [comment]
as time goes by we have to introduce new function, as I wrote in commit fa67268bbf9aef7ad47c7eeff4304f6f405df61b ,  but it seems no one cares to read this :). New function maybe (mostly) introduce new error, that's software development problem. 
By the way, can you test my newest commit?

**Comment by arty777** [comment]
--as time goes by we have to introduce new function, as I wrote in commit fa67268 , but it seems no one --cares to read this 

Where we can read about new function? What is she doing? You fixed the bug about core dumped?

**Comment by whatvn** [comment]
I believe newest commit (commited this morning) will fix your problem. Can
you test on your environment?

On Mon, Aug 10, 2015 at 2:57 PM, arty777 notifications@github.com wrote:

> as time goes by we have to introduce new function, as I wrote in commit
> fa67268
> https://github.com/whatvn/ngx_http_estreaming_module/commit/fa67268bbf9aef7ad47c7eeff4304f6f405df61b
> , but it seems no one >cares to read this
> Where we can read about new function? What is she doing? You fixed the bug
> about core dumped?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/whatvn/ngx_http_estreaming_module/issues/15#issuecomment-129347573
> .

## 

---

hungnv

**Comment by arty777** [comment]
Yes , i will test today , i will update you . Thank you

**Comment by arty777** [comment]
All fine with the lastest commit , no any core dump etc , THANK YOU (i use ffmpeg 2.7)

**Comment by whatvn** [comment]
@arty777 thanks, can you please make this test more reliable by using it in your environment, if all went well, I could mark latest commits as first release of this module.

**Comment by arty777** [comment]
already work in my prod env .  Let them work until tomorrow morning, look at stability. I will update you tomorrow

**Comment by arty777** [comment]
Completely gone from the log errors like 
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xa83620] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xa83620] overread end of atom 'colr' by 1 bytes

but we have new : 
2015/08/12 14:06:29 [alert] 11885#0: *4514652 zero size buf in output t:0 r:0 f:0 0000000000BBAB40 0000000000BBAB40-0000000000BBCB40 00000000000000
00 0-0 while sending to client, client: 1.1.1.8  server: test.example.com, request: "GET /view/org/176/89834.ts?secl=JDt7V
r23CekYUEyGdlYjcw&sect=1439406357 HTTP/1.1", upstream: "http://1.0.0.1:11/video/89834.ts?video=176&org=true&&secl=JDt7Vr22323CekYUEyGdlYjcw&sect=343
9406357", host: "1.example.com"

what is error mean? previously I had ever seen in error.log

ffmpeg info about this file

--/video# ffmpeg -i ./89834.mp4
ffmpeg version 2.7 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.6 (Ubuntu/Linaro 4.6.3-1ubuntu5)
  configuration: --enable-libx264 --enable-static --disable-opencl --enable-gpl --enable-libfdk-aac --enable-nonfree --enable-shared
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './89834.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2013-09-09 10:55:39
    title           : Wojna.mirov.Z.2013.D.HDRip.UNRATED.2100MB.INTERCINEMA
    artist          : INTERCINEMA
    encoder         : HandBrake rev0 2013051899
  Duration: 02:03:04.96, start: 0.000000, bitrate: 452 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 720x304, 319 kb/s, 23.91 fps, 23.98 tbr, 90k tbn, 180k tbc (default)
    Metadata:
      creation_time   : 2013-09-09 10:55:39
      encoder         : JVT/AVC Coding
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
    Metadata:
      creation_time   : 2013-09-09 10:55:39
At least one output file must be specified

**Comment by whatvn** [comment]
it seems the error log was produce by upstream module, not estreaming module. 
by the way, when error log occur, can you still play the file on browser or cannot download the file at all? 
Can you upload it to somewhere so I can do some check?

**Comment by arty777** [comment]
All fine after 1 day heavy load working )) , yes i can play file .

**Comment by whatvn** [comment]
did you experience swap problem with current version?

**Comment by arty777** [comment]
You mean memory usage ? all fine , approx ~150m per nginx process , it's good

**Comment by whatvn** [comment]
ok, so I mark last commit as first release of this module, any other later commit will be treated as `developing`. 
Thanks,
