### ISSUE TITLE
crit 

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#17]
2015/09/13 21:22:29 [crit] 21748#21748: _14156439 output_ts.h.808: (error) segment 1 is too big: 342577663 - 355582059, client: 127.0.0.1, server: examole.com, request: "GET /vod/filename.ts?video=1159&org=true&&secl=_********_&sect=**_*****\* HTTP/1.0", host: "example.com"

What it's mean , why it's happend , how to fix?

**Comment by whatvn** [comment]
maybe your video file contains some errors. Could you please upload it to somewhere so I can do some check?

**Comment by arty777** [comment]
can you please tell me how i can check video by myself?

**Comment by whatvn** [comment]
The first thing you should check is to make sure video metadata is placed in the beginning of your video file, in able to do that, you can use some tool/script, for example my qtfaststart: `https://github.com/whatvn/qt-faststart`

2nd, there's some video that people mixed, modified using various tools that insert many kind of stream inside one video file, that makes streaming module fail to parse or find wrong video information.

Could you please give me the output of ffmpeg -i /path/to/videofile ?

**Comment by arty777** [comment]
1. Ofcourse metadata from begining of file . Video work fine , But about the middle, in one chunk, to which the module swears, and there I get the error 500 (standart mp4 (pseudo stream) module for nginx work fine)
2. # ffmpeg -i ./issue_file.mp4
   
   ffmpeg version 2.8 Copyright (c) 2000-2015 the FFmpeg developers
   built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
   configuration: --enable-libx264 --enable-static --disable-opencl --enable-gpl --enable-libfdk-aac --enable-nonfree --enable-shared
   libavutil      54. 31.100 / 54. 31.100
   libavcodec     56. 60.100 / 56. 60.100
   libavformat    56. 40.101 / 56. 40.101
   libavdevice    56.  4.100 / 56.  4.100
   libavfilter     5. 40.101 /  5. 40.101
   libswscale      3.  1.101 /  3.  1.101
   libswresample   1.  2.101 /  1.  2.101
   libpostproc    53.  3.100 / 53.  3.100
   Input #0, mov,mp4,m4a,3gp,3g2,mj2, from './182484.mp4':
   Metadata:
     major_brand     : mp42
     minor_version   : 512
     compatible_brands: isomiso2avc1mp41
     encoder         : HandBrake 0.10.1 2015030800
   Duration: 01:48:00.83, start: 0.000000, bitrate: 453 kb/s
     Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 720x304, 320 kb/s, 23.98 fps, 23.98 tbr, 90k tbn, 180k tbc (default)
     Metadata:
       handler_name    : VideoHandler
     Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
     Metadata:
       handler_name    : Stereo
   At least one output file must be specified

**Comment by arty777** [comment]
May be you know  how to check video each frame?

**Comment by whatvn** [comment]
From ffmpeg's output, your video seems ok. you're still run with nginx 1.6.3 right?

**Comment by arty777** [comment]
no . Nginx 1.8
I have this issue  only with one videofile (i have 1000+ files wuth no any problems)

**Comment by whatvn** [comment]
if you run that file with nginx 1.6.3, do you get that problem too?

**Comment by arty777** [comment]
Yes, 1.6.3 same problem . How to understand what was a problem (with module or with file) ? 
May be you know how to check video each frame?

**Comment by arty777** [comment]
+
Sep 14 11:20:46 kvazar kernel: [1388363.718371] nginx2[29037]: segfault at 0 ip 00000000004135f7 sp 00007fffcaccf160 error 4 in nginx2[400000+a5000]

time to time on linux , with nginx 1.8

**Comment by arty777** [comment]
i go back to nginx 1.6.3 , and i  hope that you will make a universal module for different versions nginx

**Comment by whatvn** [comment]
I will work on it next week

**Comment by whatvn** [comment]
@arty777 could you please help test newest commit against nginx version 1.8 or newer?
Thanks

**Comment by arty777** [comment]
i will do all on next week , sorry 
start from monday

**Comment by arty777** [comment]
Last module version can work with both nginx 1.6 and nginx 1.8 ?

**Comment by whatvn** [comment]
I do need your test on your environment, because in my test, I never faced with core-dump error. 
I tested it on 1.8 already, and it works fine.

**Comment by arty777** [comment]
all fine , i does;t see any problem with nginx 1.8+last ver of hls module

**Comment by whatvn** [comment]
how long have you been running this version on production env?

**Comment by arty777** [comment]
7 hours ... 

we can wait high load at evening, i give feedback tomorrow morning

**Comment by arty777** [comment]
all fine

**Comment by whatvn** [comment]
Nice, close!
