### ISSUE TITLE
Flash Player doesn't have permission in crossdomain.xml

### ISSUE THREAD

**Issue by vi1421** [whatvn/ngx_http_estreaming_module#23]
Hi,
Thanks for the module,it works perfectly on ubuntu.When i'm playback it works fine with vlc and when i try to playback in http://osmfhls.kutu.ru/ im getting sandbox violation error.

Need help

**Comment by whatvn** [comment]
you should read this http://enable-cors.org/ and this http://www.adobe.com/devnet/adobe-media-server/articles/cross-domain-xml-for-streaming.html
