### ISSUE TITLE
/org/**

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#4]
http://192.168.88.2:8081/org/179/test.ts
http://192.168.88.2:8081/org/test.m3u8

is possible change "org" to custom word?

**Comment by whatvn** [comment]
No, it's not possible at current time, it's hardcode inside source code to identify request bitrate from user.
in order to change it to something else to match your need, you can change source code yourself.
Or if you have better way to identify request stream, please let me know.
Thank!
