### ISSUE TITLE
ngx_http_secure_link_module

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#5]
can you please create some conf examples to work hls module with ngx_http_secure_link_module ?

**Comment by whatvn** [comment]
I'm at step of implementing something likes this http://nginx.org/en/docs/http/ngx_http_hls_module.html?&_ga=1.235310721.1808295330.1409133637#hls_forward_args for secure_link to work. stay tune!

**Comment by whatvn** [comment]
with latest commit, you could use secure_link likes this: 

```
        secure_link           $arg_st,$arg_e;
        secure_link_md5       "axcDxSVnsGkAKvqhqOh$host$arg_e";

        if ($secure_link = "")  { return 403; }
        if ($secure_link = "0") { return 410; }

        rewrite ^(.*)/(adbr)/([0-9]+p)/([0-9]+)/(.*ts)?(.*) $1/$5?video=$4&$2=true&vr=$3&$6 last;
        rewrite ^(.*)/(adbr)/([0-9]+p)/(.*\.m3u8)?(.*) $1/$4?$2=true&vr=$3&$5 last;
        rewrite ^(.*)/(org)/(.*\.m3u8)?(.*) $1/$3?$2=true&$6 last;
        rewrite ^(.*)/(org)/([0-9]+)/(.*\.ts)?(.*) $1/$4?video=$3&$2=true&$5 last;
        rewrite ^(.*)/([0-9]+)/(.*ts)?(.*)  $1/$3?video=$2&$4 last;
        access_log logs/streaming.access.log;
```

Remember rewrite rule has been changed a little bit. With that configuration, you have to request secured link in order to access media stream: 
curl "http://localhost/test1.m3u8?st=7OBVzKXTSbFYe0ZBfNlI0A&e=2147483647"
Please check

**Comment by whatvn** [comment]
@arty777 did you manage to work with secure link module? I close this ticket now, you can re-open it later if you still have problem with it.

**Comment by arty777** [comment]
Ok , I will try to work in the near future

**Comment by arty777** [comment]
I may be interested in the question of how to use secure_link in conjunction with proxy_cache module that would cache was correct and not overwritten permanently 
May be need clean agrs? for cache
