### ISSUE TITLE
secure link+proxy  cache

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#8]
I wish to use proxy_cahe (for m3u8 and ts files) + secure_links

i see on cache files like 
KEY: http://127.0.0.1:88/video/long.m3u8?org=true&&secl=9Dl7GT9ut_cSInvjudkFHg&sect=1429630073
and 
KEY: http://127.0.0.1:88/video/long.ts?video=4&org=true&&secl=9Dl7GT9ut_cSInvjudkFHg&sect=1429630073

 but for another user (with other secure_link parameters) i will get copy cache files ... 
 I see already in the cache all the cache files for the same video ...., 10 users watch the video, and I'll have 10 copies of the same file in the cache. How can I have 1 copy of the cache for all users?

 may be i need to get on cache key like this 
KEY: http://127.0.0.1:88/video/long.m3u8
KEY: http://127.0.0.1:88/video/long.ts?video=4&org=true

 how make this correct?

**Comment by whatvn** [comment]
I will look into it

**Comment by whatvn** [comment]
hello, 
did you manage to solve this problem? 
Proxy cache has a directive called `proxy_cache_key` which you can use to specify how proxy_cache should cache the url. 
in this case, can you test with configuration: 

```
proxy_cache_key $scheme$proxy_host$uri$arg_org$arg_video;
```

**Comment by whatvn** [comment]
another thing, if you don't use transcoding function, you should not use this module.

**Comment by arty777** [comment]
proxy_cache_key $scheme$proxy_host$uri$arg_org$arg_video;

very very good!! It resolve my problem , thank you

**Comment by whatvn** [comment]
glad it works for you :)
