### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by arty777** [whatvn/ngx_http_estreaming_module#9]
what its mean in error.log ? 

source video w:720source video w:656source video w:720source video w:720source video w:720source video w:700source video w:720overread end of a
tom 'colr' by 1 bytes
source video w:704source video w:720overread end of atom 'colr' by 1 bytes
source video w:704source video w:690overread end of atom 'colr' by 1 bytes
source video w:704source video w:720source video w:720source video w:720source video w:720source video w:720source video w:720source video w:72
0source video w:720overread end of atom 'colr' by 1 bytes
.....

**Comment by whatvn** [comment]
it's just debug log. latest commit remove it from error log. Sorry about that.

**Comment by arty777** [comment]
with newest commit:
source video w:704source video w:690source video w:720overread end of atom 'colr' by 1 bytes
source video w:656source video w:720source video w:720source video w:720overread end of atom 'colr' by 1 bytes
source video w:704source video w:720source video w:720source video w:720source video w:720source video w:720source video w:720overread end of a
tom 'colr' by 1 bytes
source video w:720source video w:720source video w:720source video w:720

**Comment by arty777** [comment]
update will be? ))

**Comment by whatvn** [comment]
try again with 38002dba5c2225f8337218fd30a42034c6417229

**Comment by arty777** [comment]
new
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x121aac0] overread end of atom 'colr' by 1 bytes
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x19ba000] overread end of atom 'colr' by 1 bytes

**Comment by whatvn** [comment]
this problem is in your mp4 file. Could you please upload it to some hosting so I can download and do some check. 
Thanks

**Comment by arty777** [comment]
logger writes in what file ... Error, file a lot, probably all the mistakes ... I send an example
[cut]
you can download this file

**Comment by whatvn** [comment]
which version of ffmpeg are you using? 
Error in log file was generated by ffmpeg. May I ask which tool you use to encode this video? and which options you use?

**Comment by arty777** [comment]
i use handbrake . 
opt 
(...cut...)
after i use MP4Box to moove atom in begin of file 

ffmpeg for nginx is lastest stable 2.6.2

all work fine , but i have error in log wit hls module

**Comment by whatvn** [comment]
hmm, I can't reproduce this error, ffmpeg or error log does not show up that error.

**Comment by arty777** [comment]
tell me , how via mpeg i can reproduce this error? 
I gave the file at random may not hit the wrong, because nginx does not write to the log file to which it is a mistake

**Comment by whatvn** [comment]
ffmpeg -i filename , look at output log you should see the error 

##
